# Generated by Django 2.0 on 2018-01-11 12:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djinn_contenttypes.models.base
import djinn_contenttypes.models.relatable
import djinn_contenttypes.models.sharing
import markupfield.fields
import pgauth.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('removed_creator_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creator naam')),
                ('userkeywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('is_tmp', models.BooleanField(default=False, verbose_name='Temporary')),
                ('text', markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True, verbose_name='Text')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='Status')),
                ('text_markup_type', models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain')], default='plain', editable=False, max_length=30)),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('_text_rendered', models.TextField(editable=False, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
            bases=(models.Model, pgauth.base.LocalRoleMixin, djinn_contenttypes.models.sharing.SharingMixin, djinn_contenttypes.models.relatable.RelatableMixin),
        ),
        migrations.CreateModel(
            name='AnnouncementUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date')),
                ('text', markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True, verbose_name='Text')),
                ('text_markup_type', models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain')], default='plain', editable=False, max_length=30)),
                ('_text_rendered', models.TextField(editable=False, null=True)),
            ],
            options={
                'ordering': ('date',),
            },
            bases=(models.Model, djinn_contenttypes.models.base.FKContentMixin),
        ),
        migrations.CreateModel(
            name='ServiceAnnouncement',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djinn_announcements.Announcement')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='(Expected) end date')),
                ('remove_after_publish_to', models.BooleanField(default=False, verbose_name='Remove the content after publication to has past')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link')),
            ],
            options={
                'ordering': ('-start_date', '-created'),
            },
            bases=('djinn_announcements.announcement',),
        ),
        migrations.AddField(
            model_name='announcementupdate',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='djinn_announcements.Announcement'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='parentusergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_parentusergroup', to='pgauth.UserGroup'),
        ),
    ]
