# Generated by Django 2.0.13 on 2024-11-17 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceannouncement',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcement_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcement_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceannouncement',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, help_text='Naar verwachting eindigt de storing/onderbreking op dit tijdstip', null=True, verbose_name='(Expected) end date'),
        ),
        migrations.AlterField(
            model_name='serviceannouncement',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, help_text='Tijdstip waarop de dienstverlening is of wordt onderbroken (start storing of onderhoud)', null=True, verbose_name='Start date'),
        ),
    ]
